---
title: "Library books"
author: "Mark Hagemann"
date: "2014-08-23"
output: html_document
---

One of my favorite things about being at a major research university is having access to a tremendous collection of library books. I'm overwhelmed not only by the number available to me, but also the generosity of the loan duration. I don't know exactly how long the loans are, but it's got to be at *least* six months. Which really encourages the kind of borrowing I've taken to doing--checking out books on the slightest whim and with only a vague idea of when or if I'll get around to reading them. This behavior has ramped up recently, and at last count I think I had 19 books checked out--some I've already read, a few I'm currently in the middle of, and others that I strongly doubt I'll ever get around to. 

The reason I mention this is that I'm about to return my first batch of books, after getting an email reminding me that even gratuitous loan periods come to an end. These books are: 

- Prospectives on Contemporary Statistics - D. Hoaglin and D. Moore, eds.
- An Introduction to Mathematical Philosophy - Bertrand Russell
- An Introduction to C.S. Peirce - Robert Corrington
- Peirce and Pragmatism - W.B. Gallie
- The Philosophy of Charles S. Peirce - Robert Almeder

Of these five books, I read a few pages of the first, some two or three chapters of the second, and practically none of the remaining three. I'll briefly explain. 

As you can probably tell, I've become interested in philosophy, specifically the philosophy of knowledge as it pertains to statistical and mathematical evidence. It's an interest that arose out of a "what does it all mean?!" moment in my graduate research, and one that I was wholly unprepared for academically. Hence my frantic first steps trying to find the relevant foundational literature. 

The *Perspectives...* collection was sort of a result of grabbing the first relevant-seeming thing I saw; I will say it did a good job of condensing the essence of what statistics in its broadest sense tries to accomplish, though it stopped short of mentioning words like "epistemology" or "ontology". 

For some reason I thought that Peirce's "pragmatic" school of epistemology was something that I needed to get on board with. Thankfully, before I had waded very far into any of the three books I'd checked out on that subject, I got a primer from a much more accessible (entertaining, even!) source--Martin Gardner's *The Whys of a Philosophical Scrivener*--which set me straight on how esoteric and (ironically) devoid of utility the subject was. 

I was similarly misled by the idea of "mathematical philosophy", which it turns out is an entirely different topic from "philosophy of mathematics," which would have done more to scatch my itch. My misunderstanding on this score was only half the reason I got the Russell book, though; the other half was the opportunity to read more of Russell's work (I'd already developed a bit of an academic-crush on the guy). 

I like this idea of reviewing library books as I return them; I think I'll try to make it a habit. No new due-date notices yet, though. 